version: '2.1'

volumes:
  pihole:
  dnsmasq:
  
services:
  pihole:
    image: pihole/pihole:4.1.1_armhf
    ports:
     - '80:80/tcp'
     - '80:80/udp'
    volumes:
      - 'pihole:/etc/pihole'
      - 'dnsmasq:/etc/dnsmasq.d'
    entrypoint: ['/bin/bash', '-c', 'echo "bind-interfaces" >> /etc/dnsmasq.conf; /s6-init']
    network_mode: host
